### ISSUE TITLE
More feedback (mainly TROX)

### ISSUE THREAD

**Issue by spjakob** [eriknn/ha-modbus_tcpip#3]
Installed 1.0 now and tried to start to migrate to this for "production". 
As I said before I'm super happy with this integration and now stuff seems stable and works great.

Below is some feedback and I think I have mentioned some things before, however I now used this a bit more and trying to give some more perspective.

1. For me this is really top 1, 2 and 3 priority. Would really, really, be great if there could be some way make trox work with selected unit of measurment instead of converting to m3/s. Prefered unit may be personal, based on country or type of installation, but for me, _everything_ is in l/s and this is what's displayed in graph:s etc. and having to manually convert to/from m3/h when displaying or changing data has already made me do a few errors.

2. This is just a minor thing, but I still think the most common use scenario is to set flow to an actual number, not to a percentage of nominal flow. I can do both now, but the one I used most is in "Configuration" section, not "Control". 

3. Just changing dropdown for configuration generates a message in "logbook", should it really do this since  I doesn't change anything? Also, if I do change a value, nothing is written in logbook (I think at least "old casa" wrote in logbook when I changed values, and it's really nice to have this to keep track of changes done.... 

About Casa:
I'm not able to add R15, or actually I can but no entities show up...  but if I input exactly same data and add it as R4, it's added and all entities show up.

I'll continue to use and test and my goal for Chrismas hollidays is to write an file for my SDM630 Energy meters and my Grundfos  pump, then can I switch completely to this integration

Thanks again for your work. Let me know if you would prefer that I make separate issues in future....  I think this is maybe a better way now that everything get more stable...

**Comment by eriknn** [comment]
1. I would change to l/s if it was a HA official unit. But it's not. I think many people want this, so the only way to get it is to push this as an issue in the official HA-channels!
2. Trox TVE only accepts setpoint as percent on register 0. This is tpical for all dampers I have encountered. Where I've wanted the same as you, I've had to convert to percent as well. The parameters in configuration are for _configuration_ and max/min values. Not for control
3. For me, setting any drop down value, or activating switching will be logged. Changing numeric values are not logged in any of my integrations. I think this is all defined by Home Assistant defaults, and not something I can change.
4. CASA R15 had a bug, will release with fix

**Comment by spjakob** [comment]
1. I understand about l/s and could try to run this through the official HA-channels, but with latest change it seems like now there is actual support for l/s if this is the setting for device? 
2.
I understand what you say and it seems that you have a lot of more experience with this types of units than me. Maybe I'm using my units in a wrong way and I will try to understand this better.... I have used the qvmin to control the flow based on actual values (as in 5.2.3 in manual)  and this was based on my communication with trox people... I'll investigate this more.... 

3.
Below is and image for the "old casa" integration, where I a) choose "Home exhaust speed" b) change value
![image](https://github.com/user-attachments/assets/5a93be3d-bffe-44fa-b6e1-1f98cb50ed2b)
The value change is logged here, but not in new integration. Not a big issue and I really don't know how logger is supposed to work or what's possible. I only think that from a logical point of view it would make sense to log any actual changes to the device and less important to log any interaction with UI that doesn't change values. But I understand  if this is beyond your control.
4. I can confirm that this is now working.

5. I also tried to create a new entry with wrong slave id and the behavior now is much better, device is created, but fails to initialize:
![image](https://github.com/user-attachments/assets/3e5e9439-d657-4bcd-a4ee-beb113318983)
...and after pressing configure and entering correct id, everything is "solved". NICE! :)

**Comment by eriknn** [comment]
1. About l/s - it’s possible to have anything as a unit, you could use the units «awesomeJakobs» if you wanted to. But just like «l/s», HA wouldn’t know what to do with it, except add it after the numbers. With supported units, HA allows the user to select conversions to other units etc. So when possible, supported units shouod be preferred.

In this case I thought I had to select one type as default, but I figured how I could change it dynamically, so there you go - we’ll use the same as the device.
2. Some units use memory that shouldn’t be written often for these types of values. I guess you leave the percentage sp at 0 then, and control with minimum flow? If that works then so be it…
3. I’ll have a look at it when I have more time, other priorities forward. I really have no idea how this works, so need to read up a bit…

Great that the other stuff is working :)

**Comment by spjakob** [comment]
Den mån 16 dec. 2024 kl 00:49 skrev eriknn ***@***.***>:

>
>    1. About l/s - it’s possible to have anything as a unit, you could use
>    the units «awesomeJakobs» if you wanted to. But just like «l/s», HA
>    wouldn’t know what to do with it, except add it after the numbers. With
>    supported units, HA allows the user to select conversions to other units
>    etc. So when possible, supported units shouod be preferred.
>
> In this case I thought I had to select one type as default, but I figured
> how I could change it dynamically, so there you go - we’ll use the same as
> the device.
>

Ok this is how I thought it was now. Great solution and works for me. Let's
hope HA officially supports l/s in future also.

> 2. Some units use memory that shouldn’t be written often for these types
> of values. I guess you leave the percentage sp at 0 then, and control with
> minimum flow? If that works then so be it…
>

Yes, this is correct. This is how I do now and to my understanding, this is
the suggested way to do this by trox. Percentage can not even be set
locally on device, only via modbus. For local regulation only changing
Qvmin is supported for fixed flow.
Off course same result can be achived by changing register 0 also.


> 3. I’ll have a look at it when I have more time, other priorities forward.
> I really have no idea how this works, so need to read up a bit…
>

Ok, this is absolutely not a big issue.

**Comment by eriknn** [comment]
If you are running fixed flow, then you can set qmin = qmax.
User manual 5.2.3 doesn't intend to change the setpoint alot (maybe you don't either)

```
8.5.2.1 Setting the entire control range for the
control input signal of the central building
management system
If the volume flow rate is to be scpecified by the central BMS across the entire control range, Qvmin must be set to 0 m³/h and Qvmax to Qvnom.
```
This would be my preferred way to control the VAV.

![image](https://github.com/user-attachments/assets/aa3bf206-fbd8-4289-9da7-80c37248f00b)

Here you see how parameter 0 is designed to be used for "dynamic control". In practice, this is probably not a problem, but you don't want to write a new value to EEPROM-values every 10 minutes or so...

**Comment by eriknn** [comment]
I’m closing this as it had many points, and most should be fixed. Feel free to raise new issues - I’m pretty sure there’s room for more improvements :)
