### ISSUE TITLE
Changing name not working 100%

### ISSUE THREAD

**Issue by spjakob** [eriknn/ha-modbus_tcpip#4]
1. Add a new device.
2. Press configure and change name.
3. Name is changed in "device list", but is still the same (old) in " Integration entries " ?

**Comment by eriknn** [comment]
Yeah, I’ve been aware of some oddities here. I’ve got several integrations with different ways to handle several devices - some use one integration instance per device, some use one integration instance with multiple devices.
I think in your case, one name might be the integration instance name, and one the device name. Or something like that.
I need to look into this, but I think I’m using the device name as a lookup-key for the integration configuration, so it’s easy to make a stupid breaking change that requires re-add of all devices.
It’s high up on the list of priorities…

**Comment by eriknn** [comment]
Okay, so here's the deal:
When adding a device, an instance of the integration is created + a device. They both are named what you call the device. Later changes to the name will only affect the device, and not the integration instance.
I changed this now, so both are updated, and it looks like it now behaves more as expected. I think you still can override the device name after clicking on the device, but that's default HA-behaviour.
